server:
  port: 8082

spring:
  application:
    name: report-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/${MY_AZURE_TENANT_ID}/

app:
  oauth2:
    token-uri: https://login.microsoftonline.com/${MY_AZURE_TENANT_ID}/oauth2/v2.0/token
    client-id: ${MY_SERVICE_CLIENT_ID}
    client-secret: ${MY_SERVICE_CLIENT_SECRET}
    scope: api://${MY_SCOPE}/.default
  user-service:
    users-uri: ${USER_SERVICE_USERS_URI:http://localhost:8081/api/users}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.servlet.function: DEBUG